# Generated by Django 2.2.9 on 2020-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('Bi', 'Binary'), ('No', 'Nominal'), ('In', 'Interval'), ('Ra', 'Ratio')], max_length=10)),
                ('data_type', models.CharField(choices=[('Nu', 'Numeric'), ('Ch', 'Character'), ('Da', 'Date')], max_length=10)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Co', 'Company'), ('Cy', 'Country')], max_length=10)),
            ],
        ),
    ]
